name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer PHP et les dépendances
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_mysql
          coverage: none

      - name: Installer Composer
        run: composer install --no-progress --no-suggest

      - name: Lancer les tests unitaires
        run: ./vendor/bin/phpunit --testdox
